name: irfanview
title: IrfanView (WINE)
summary: IrfanView is a compact and lightweight image viewer.
description: |
 IrfanView is a fast and simple freeware image viewer, editor and converter that supports all major graphic formats that can open, edit, or convert most common image formats including AIF, DJVU, GIF, ICO, JPG, PNG, PSD, RAW, TGA, TIF...etc. and can be further extended via plug-ins that are widely available. Use it to quickly browse through a directory of pictures, convert images from one format to another, crop, rotate, optimize an image, create a slideshow and even view movies or play audio files (MP3, AVI, audio CDs, and WMA). IrfanView features include drag & drop support, directory viewing, TWAIN support, batch conversion, image editing, Photoshop filters support, paint options, image modifications such as color depth, crop, blur, sharpen, image resizing, cropping and more.
adopt-info: irfanview

confinement: strict
grade: stable
architectures:
  - build-on: amd64
  - build-on: i386
base: core18
compression: lzo

plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-6-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-6-stable

environment:
  WINEDLLOVERRIDES: "mscoree,mshtml=" # Prevent pop-ups about Wine Mono and Wine Gecko
  RUN_EXE: "$SNAP_USER_DATA/irfanview/irfanview.exe"
  SOMMELIER_KEEP_CWD: "1" # Don't change the working directory so relative paths still work
  NO_AT_BRIDGE: "1" # Fix yad error Failed to connect to socket /tmp/dbus-xxx: No such file or directory

apps:
  irfanview:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier run-exe
    plugs:
      - opengl
      - home
      - network
      - hardware-observe
      - process-control
      - cups-control
      - removable-media
    desktop: usr/share/applications/irfanview.desktop
  # The wine command can be used to run applications inside the wine
  # environment that this snap uses.
  #
  # For example, users can configure the wine environment of this snap
  # by running `myapp.wine winecfg`.
  wine:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier
    plugs:
      - home
      - network
      - hardware-observe
      - process-control
      - cups-control
      - removable-media
  # The winetricks command can be used to run winetricks inside the wine
  # environment that this snap uses.
  winetricks:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  irfanview:
    plugin: nil
    source: ./snap/local/src
    override-build: |
      snapcraftctl build
      set -ex
      ver=$(wget https://www.irfanview.com -q -S -O - 2>&1 | grep 'Version' | sed 's|</| |' | awk '{print $2}')
      snapcraftctl set-version "$ver"
      ./dl_ifv
    stage:
      - bin
      - usr
      - wine-platform
      - wine-runtime
      - sommelier
    build-packages: [wget]
  # The sommelier script helps you snap Windows applications using Wine. It
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/mmtrt/sommelier-core.git
    source-branch: "tmp"
